Web/ShortlistManager.Web/Controllers/SyncController.cs
using System.Web.Mvc;
using ShortlistManager.Services;
using ShortlistManager.Services.Models;
using ShortlistManager.Web.Infrastructure.Auth;
using ShortlistManager.Web.Infrastructure.Filters.ModelState;

namespace ShortlistManager.Web.Controllers
{
    [UserDetailsProviderFilter]
    public class SyncController : Controller
    {
        /*
            > Using the PRG pattern
            > I would generally prefer to have a seperate view model class, rather than pushing 
              the dto straight to the view, but in this case the dto is just a bag of properties, and
              I'm reluctant to duplicate the object at each layer when there's little benefit to doing so.
         */

        private readonly IShortlistService _shortlistService;

        public SyncController(IShortlistService shortlistService)
        {
            _shortlistService = shortlistService;
        }


        [HttpGet]
        public ViewResult Index(UserDetails userDetails)
        {
            var players = _shortlistService.PlayersForScout(userDetails.Id);
            return View(players);
        }

        [HttpGet]
        [RetrieveModelState]
        public ViewResult Edit(UserDetails userDetails, int? id)
        {
            var player = id == null
                ? new PlayerDto()
                : _shortlistService.GetPlayer(userDetails.Id, id.Value);

            return View(player);
        }

        [HttpPost]
        [PersistModelState]
        public RedirectToRouteResult Edit(UserDetails userDetails, PlayerDto viewModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Edit", new {id = viewModel.Id});
            }

            _shortlistService.AddPlayer(userDetails.Id, viewModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ViewResult ConfirmDelete(UserDetails userDetails, int id)
        {
            var player = _shortlistService.GetPlayer(userDetails.Id, id);
            return View(player);
        }

        [HttpPost]
        public RedirectToRouteResult Delete(UserDetails userDetails, int id)
        {
            _shortlistService.RemovePlayer(userDetails.Id, id);
            return RedirectToAction("Index");
        }

    }
}

Web/ShortlistManager.Web/Views/Sync/ConfirmDelete.cshtml
@model ShortlistManager.Services.Models.PlayerDto

<h2>Delete Player</h2>

<h3>Are you sure you want to delete this player?</h3>
<div>   
    @Html.Partial("_Details", Model)

    @using (Html.BeginForm("Delete", "Sync", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="hidden" name="id" value="@Model.Id" />
            <input type="submit" value="Delete" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/ShortlistManager.Web/Views/Sync/Edit.cshtml
@model ShortlistManager.Services.Models.PlayerDto

@Html.Partial("_Form", Model)

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts{
    @Scripts.Render("~/js/jquery-helpers")
}

Web/ShortlistManager.Web/Views/Sync/Index.cshtml
@model IEnumerable<ShortlistManager.Services.Models.PlayerDto>

<div style="margin-top: 32px;">
    @Html.Partial("_Table", Model)
</div>

<p>
    <a class="btn btn-default" href="@Url.Action("Edit")">Add</a>
</p>

Web/ShortlistManager.Web/Views/Sync/_Details.cshtml
@model ShortlistManager.Services.Models.PlayerDto

<dl class="dl-horizontal">
    <dt>@Html.DisplayNameFor(model => model.FirstName)</dt>
    <dd>@Html.DisplayFor(model => model.FirstName)</dd>
    <dt>@Html.DisplayNameFor(model => model.Surname)</dt>
    <dd>@Html.DisplayFor(model => model.Surname)</dd>
    <dt>@Html.DisplayNameFor(model => model.ClubName)</dt>
    <dd>@Html.DisplayFor(model => model.ClubName)</dd>
    <dt>@Html.DisplayNameFor(model => model.DateOfBirth)</dt>
    <dd>@Html.DisplayFor(model => model.DateOfBirth)</dd>
</dl>

Web/ShortlistManager.Web/Views/Sync/_Form.cshtml
@model ShortlistManager.Services.Models.PlayerDto

@{ var heading = Model.Id == 0 ? "Add Player" : "Edit Player"; }

<h2>@heading</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClubName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClubName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClubName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Web/ShortlistManager.Web/Views/Sync/_Table.cshtml
@model IEnumerable<ShortlistManager.Services.Models.PlayerDto>


<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.FirstName)</th>
        <th>@Html.DisplayNameFor(model => model.Surname)</th>
        <th>@Html.DisplayNameFor(model => model.ClubName)</th>
        <th>@Html.DisplayNameFor(model => model.DateOfBirth)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
            <td>@Html.DisplayFor(modelItem => item.Surname)</td>
            <td>@Html.DisplayFor(modelItem => item.ClubName)</td>
            <td>@Html.DisplayFor(modelItem => item.DateOfBirth)</td>
            <td>
                <a href="@Url.Action("Edit", new {id = item.Id})" class="btn btn-default">Edit</a>
                <a href="@Url.Action("ConfirmDelete", new { id = item.Id })" class="btn btn-default">Delete</a>
            </td>
        </tr>
    }

</table>