Web/ShortlistManager.Web/Controllers/SpaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ShortlistManager.Services;
using ShortlistManager.Services.Models;
using ShortlistManager.Web.Infrastructure.Auth;
using ShortlistManager.Web.Infrastructure.ErrorHandling;

namespace ShortlistManager.Web.Controllers
{
    [UserDetailsProviderFilter]
    public class SpaController : Controller
    {
        private readonly IShortlistService _shortlistService;

        public SpaController(IShortlistService shortlistService)
        {
            _shortlistService = shortlistService;
        }

        [HttpGet]
        public ActionResult Index(UserDetails userDetails)
        {
            return View();
        }


        [HttpGet]
        [OutputCache(Duration = 0)]
        public JsonResult ListPlayers(UserDetails userDetails)
        {
            var players = _shortlistService.PlayersForScout(userDetails.Id);
            return Json(players, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [OutputCache(Duration = 0)]
        public ActionResult GetPlayer(UserDetails userDetails, int id)
        {
            var playersForScout = _shortlistService.PlayersForScout(userDetails.Id);
            var playerWithId = playersForScout.SingleOrDefault(x => x.Id == id);

            return Json(playerWithId, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public HttpStatusCodeResult SavePlayer(UserDetails userDetails, PlayerDto player)
        {
            if (!ModelState.IsValid)
            {
                var errorMessage = ExtractErrorMessage(ModelState);
                throw new ValidationException(errorMessage);
            }

            _shortlistService.AddPlayer(userDetails.Id, player);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }


        [HttpPost]
        public HttpStatusCodeResult DeletePlayer(UserDetails userDetails, int id)
        {
            _shortlistService.RemovePlayer(userDetails.Id, id);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        private static IEnumerable<string> ExtractErrorMessage(ModelStateDictionary modelState)
        {
            return (from key in modelState.Keys
                    from msg in modelState[key].Errors.Select(x => x.ErrorMessage)
                    select $"{key}: {msg}");
        }

    }
}

Web/ShortlistManager.Web/Views/Spa/Index.cshtml
@{
    ViewBag.Title = "Shortlist";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script type="text/javascript">
        var url_Shortlist_ListPlayers = '@Url.Action("ListPlayers", "Spa")';
        var url_Shortlist_GetPlayer = '@Url.Action("GetPlayer", "Spa")';
        var url_Shortlist_SavePlayer = '@Url.Action("SavePlayer", "Spa")';
        var url_Shortlist_DeletePlayer = '@Url.Action("DeletePlayer", "Spa")';
    </script>

    @Scripts.Render("~/js/ng")
    @Scripts.Render("~/js/ng-ShortlistApp")
}

<div ng-app="shortlistApp" class="ng-cloak">

    <div ng-repeat="msg in messages" class="alert {{msg.style}} alert-dismissible alert-container" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>{{msg.prefix}}</strong>
        <span class="alert alert-content">{{msg.content}}</span>
    </div>

    <div>
        <div ng-view></div>
    </div>
</div>